### ISSUE TITLE
Allow risky rules

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/beautifier-php-cs-fixer#23]
Is it possible to add the flag `--allow-risky`? 

Error from vscode:
```
[Extension Host] Using config: --config=/Users/marvinheilemann/Documents/Customers/Additive/Website/Joomla/.php_cs
2console.ts:136 [Extension Host] Loaded config default from "/Users/marvinheilemann/Documents/Customers/Additive/Website/Joomla/.php_cs".

In ConfigurationResolver.php line 343:
                                                                               
  The rules contain risky fixers (no_php4_constructor, dir_constant, moderniz  
  e_types_casting, no_unreachable_default_argument_value), but they are not a  
  llowed to run. Perhaps you forget to use --allow-risky option?
```

**Comment by Glavin001** [comment]
The current way to do this would be using `.php_cs` or `.php_cs.dist` config files: https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file
Combined with using `prefer_beautifier_config` Unibeautify option: https://unibeautify.com/docs/beautifier-php-cs-fixer.html#advanced
Take a look at these sub-folders: https://github.com/Unibeautify/beautifier-php-cs-fixer/tree/master/test/preferBeautifierConfig

Since `allow-risky` is not applicable to other beautifiers or languages it does not make sense to add to Unibeautify's options registry: https://unibeautify.com/docs/options-for-languages.html
Unibeautify may support more beautifier-specific options in the future.  However, for now only `prefer_beautifier_config` is available: https://unibeautify.com/docs/options-for-beautifiers.html

**Comment by muuvmuuv** [comment]
Would be nice to have that option in the future, as for now, I have to disable the risky rules until I can pass that flag to the beautifier.

**Comment by Glavin001** [comment]
> Would be nice to have that option in the future,

Support for this in Unibeautify is very low priority considering all of the other things @szeck87 are currently working on.

> I have to disable the risky rules until I can pass that flag to the beautifier.

@muuvmuuv You do not need to disable risky rules. I recommend you create a `.php_cs` configuration file for PHP-CS-Fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file
Contact the maintainers of PHP-CS-Fixer for questions about their configuration file.

This is how Unibeautify officially supports non-supported options, by allowing you to pass in the beautifier's own configuration format.

**Comment by szeck87** [comment]
@muuvmuuv can you post a link to your configuration file?  Should be pretty easy to add in there.

**Comment by muuvmuuv** [comment]
@szeck87 sure: https://pastebin.com/6eix1a2Q note that I commented out the risky rules (and some others)

**Comment by szeck87** [comment]
Yea, just add `->setRiskyAllowed(true)`.

**Comment by Glavin001** [comment]
Pull Requests welcome to add some details to the README, such as an FAQ section.

**Comment by muuvmuuv** [comment]
Ahhh, thanks @szeck87. Did not know that!
